const goals = [
    {
        id: 1,
        image: 'sdg/E-WEB-Goal-01.png',
        title: 'No Poverty',
        description: 'End poverty in all its forms everywhere',
        alt: 'No Poverty',
        link: '/sdg/goal/1',
    },
    {
        id: 2,
        image: 'sdg/E-WEB-Goal-02.png',
        title: 'Zero Hunger',
        description: 'End hunger, achieve food security and improved nutrition and promote sustainable agriculture',
        alt: 'Zero Hunger',
        link: '/sdg/goal/2',
    },
    {
        id: 3,
        image: 'sdg/E-WEB-Goal-03.png',
        title: 'Good Health and Well-being',
        description: 'Ensure healthy lives and promote well-being for all at all ages',
        alt: 'Good Health and Well-being',
        link: '/sdg/goal/3',
    },
    {
        id: 4,
        image: 'sdg/E-WEB-Goal-04.png',
        title: 'Quality Education',
        description: 'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all',
        alt: 'Quality Education',
        link: '/sdg/goal/4',
    },
    {
        id: 5,
        image: 'sdg/E-WEB-Goal-05.png',
        title: 'Gender Equality',
        description: '',
        alt: 'Gender Equality',
        link: '/sdg/goal/5',
    },
    {
        id: 6,
        image: 'sdg/E-WEB-Goal-06.png',
        title: 'Clean Water and Sanitation',
        description: 'Ensure availability and sustainable management of water and sanitation for all',
        alt: 'Clean Water and Sanitation',
        link: '/sdg/goal/6',
    },
    {
        id: 7,
        image: 'sdg/E-WEB-Goal-07.png',
        title: 'Affordable and Clean Energy',
        description: 'Ensure access to affordable, reliable, sustainable and modern energy for all',
        alt: 'Affordable and Clean Energy',
        link: '/sdg/goal/7',
    },
    {
        id: 8,
        image: 'sdg/E-WEB-Goal-08.png',
        title: 'Decent Work and Economic Growth',
        description: 'Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all',
        alt: 'Decent Work and Economic Growth',
        link: '/sdg/goal/8',
    },
    {
        id: 9,
        image: 'sdg/E-WEB-Goal-09.png',
        title: 'Industry, Innovation, and Infrastructure',
        description: 'Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation',
        alt: 'Industry, Innovation, and Infrastructure',
        link: '/sdg/goal/9',
    },
    {
        id: 10,
        image: 'sdg/E-WEB-Goal-10.png',
        title: 'Reduced Inequality',
        description: 'Reduce inequality within and among countries',
        alt: 'Reduced Inequality',
        link: '/sdg/goal/10',
    },
    {
        id: 11,
        image: 'sdg/E-WEB-Goal-11.png',
        title: 'Sustainable Cities and Communities',
        description: 'Make cities and human settlements inclusive, safe, resilient and sustainable',
        alt: 'Sustainable Cities and Communities',
        link: '/sdg/goal/11',
    },
    {
        id: 12,
        image: 'sdg/E-WEB-Goal-12.png',
        title: 'Responsible Consumption and Production',
        description: 'Ensure sustainable consumption and production patterns',
        alt: 'Responsible Consumption and Production',
        link: '/sdg/goal/12',
    },
    {
        id: 13,
        image: 'sdg/E-WEB-Goal-13.png',
        title: 'Climate Action',
        description: 'Take urgent action to combat climate change and its impacts',
        alt: 'Climate Action',
        link: '/sdg/goal/13',
    },
    {
        id: 14,
        image: 'sdg/E-WEB-Goal-14.png',
        title: 'Life Below Water',
        description: 'Conserve and sustainably use the oceans, seas and marine resources for sustainable development',
        alt: 'Life Below Water',
        link: '/sdg/goal/14',
    },
    {
        id: 15,
        image: 'sdg/E-WEB-Goal-15.png',
        title: 'Life on Land',
        description: 'Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss',
        alt: 'Life on Land',
        link: '/sdg/goal/15',
    },
    {
        id: 16,
        image: 'sdg/E-WEB-Goal-16.png',
        title: 'Peace, Justice, and Strong Institutions',
        description: 'Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all',
        alt: 'Peace, Justice, and Strong Institutions',
        link: '/sdg/goal/16',
    },
    {
        id: 17,
        image: 'sdg/E-WEB-Goal-17.png',
        title: 'Partnerships for the Goals',
        description: 'Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development',
        alt: 'Partnerships for the Goals',
        link: '/sdg/goal/17',
    },
];

export default goals;